ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('story-1/', include('story1.urls')),
    path('', include('story7.urls')),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('accordion/', views.accordion, name='accordion'),
    path('booksfinder/', views.booksfinder, name='booksfinder'),
    path('user/login', views.loginpage, name='login'),
    path('user/logout', views.logoutuser, name='logout'),
    path('user/register', views.registeruser, name='registeruser'),
]

story7/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    book_id = models.CharField(max_length=25)
    book_title = models.CharField(max_length=200)
    book_img = models.CharField(max_length=250)
    book_link = models.CharField(max_length=200)
    count_like = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.book_title

story7/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

story7/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .models import Book
from .forms import CreateUserForm

# Create your views here.


def accordion(request):
    return render(request, 'story7/accordion.html')

def booksfinder(request):
    return render(request, 'story7/booksfinder.html')

def loginpage(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('profile:index')
        else:
            messages.info(request, "Incorrect Username or Password")

    return render(request, 'story7/login.html')

def logoutuser(request):
    logout(request)
    return redirect('story7:login')

def registeruser(request):
    if request.user.is_authenticated:
        return redirect ('profile:index')
        
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Register Successful!")

            return redirect('story7:login')

    context = {'form': form
    }
    return render(request, 'story7/registeruser.html', context)    

story7/templates/story7/accordion.html
{% extends "base.html" %}

{% block meta %}
<title>Accordion</title>
{% endblock meta %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/accordion.css' %}">
<div class="wrapper col-12">
    <div class="d-flex flex-column justify-content-start align-items-center py-5 col-lg-8 mx-auto">
        <h1 class="mb-2">Hi, I am <b>Faris Ardhafa</b>!</h1>
        <div class="accordion col-md-10 p-0 mt-2 accordion-1" id="accor1">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Introduction</h2>
                <div class="buttons d-flex justify-content-end justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>Hi, I’m Faris Ardhafa - 20 years old</p>
                    <p>I am interested in learning data and looking forward to please my clients for my work.</p>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-2" id="accor2">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Current Activities</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>My current activities are as follows:</p>
                    <ul class="m-0">
                        <li>Watching youtube videos</li>
                        <li>Playing some games</li>
                        <li>Reading books/literature</li>
                        <li>Learning online</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-3" id="accor3">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Experiences</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>I don't have many experiences yet, but here they are</p>
                    <ul class="m-0">
                        <li>Staff at COMPFEST</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-4" id="accor4">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Achievements</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>My achievements are...</p>
                    <ul class="m-0">
                        <li>Accepted at Fasilkom UI</li>
                        <li>Fast progress at some games</li>
                        <li>Joining a comittee for the first time recently</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-5" id="accor5">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Contact</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0 d-flex flex-column">
                    <div class="d-flex mt-2">
                        <img src="https://www.stickpng.com/assets/images/58e91afdeb97430e81906504.png" height="30"
                            width="30" class="mr-2">
                        <h4><a href="https://www.linkedin.com/in/faris-ardhafa-33562b1a0/">LinkedIn</a></h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="change-theme d-flex align-items-center mt-4">
            <h4 class="mr-2">Dark Mode</h4>
            <input type="checkbox" hidden="hidden" id="theme">
            <label class="switch" for="theme"></label>
        </div>
    </div>
</div>
<script src="{% static 'js/accordion.js' %}"></script>
{% endblock %}

story7/templates/story7/booksfinder.html
{% extends "base.html" %}
{% load static %}


{% block meta %}
<title>Books</title>
{% endblock meta %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/booksfinder.css' %}">

<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <div class="form-group col">
                <h2>Books Finder</h2>
                <div class="searchbox">
                <input id="search" class="form-control" placeholder="title or genre..">
                </div>
            </div>
            <div class="form-group col-auto">

                <div class="mytable">
                    <div style="overflow-x:auto;">
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col-2">No.</th>
                                    <th scope="col-2">Cover</th>
                                    <th scope="col-2">Title</th>
                                    <th scope="col-2">Author</th>
                                </tr>
                            </thead>
                            <tbody class="result">
                                <!-- Ajax Content -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/booksfinder.js' %}"></script>
{% endblock %}

story7/templates/story7/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% load static %}


{% block meta %}
<title>Register</title>
{% endblock meta %}
{% csrf_token %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">

<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" name="password" placeholder="Password..." class="form-control">
                    </div>

                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Login">
                    </div>
                </form>

            </div>

            {% for i in messages %}
                <p id="messages">{{ i }}</p>
            {% endfor %}

            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a style="color: rgba(250, 240, 255, 0.87);" href="{% url 'story7:registeruser' %}" class="ml-2">Sign Up</a>
                </div>

            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
    integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
{% endblock %}

story7/templates/story7/registeruser.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% load static %}


{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/registeruser.css' %}">

<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">REGISTER ACCOUNT</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" name="password1" placeholder="Password..." class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" name="password2" placeholder="Re-enter Password..." class="form-control">
                    </div>

                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Register Account">
                    </div>
                </form>
            </div>

            {{ form.errors }}

            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a style="color: rgba(250, 240, 255, 0.87);" href="{% url 'story7:login' %}" class="ml-2">Login</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
    integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<script src="{% static 'js/booksfinder.js' %}"></script>
{% endblock %}