ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('story-1/', include('story1.urls')),
    path('', include('story7.urls')),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

#url for app, add your URL Configuration
app_name = 'profile'

urlpatterns = [
    #TODO Implement this
    path('', views.index, name='index'),
    path('gallery/', views.gallery, name='gallery'),
    path('course/add', views.course_add, name='add_course'),
    path('course/update/<str:pk>', views.course_update, name='update_course'),
    path('course/delete/<str:pk>', views.course_delete, name='delete_course'),
    path('course/detail/<str:pk>', views.course_detail, name='detail_course'),
    path('course/', views.course, name='course'),
    path('activity/', views.activity, name='activity'),
    path('register/<str:pk>', views.register, name='register'),
]

story4/models.py
from django.db import models

# Create your models here.


class Activity(models.Model):

    class Meta:
        verbose_name_plural = 'Activities'
    name = models.CharField(max_length=50)
    

class Person(models.Model):

    name = models.CharField(max_length=50)

    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)


class Course(models.Model):
    name = models.CharField(max_length=50)
    lecturer = models.CharField(max_length=80)
    credit = models.CharField(max_length=10)
    description = models.TextField()
    year = models.CharField(max_length=20)
    room = models.CharField(max_length=10)

    def __str__(self):
        return self.name

story4/forms.py
from django import forms
from .models import Course, Activity, Person


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = (
            'name',
        )

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = (
            'name',
            'lecturer',
            'credit',
            'description',
            'year',
            'room',
        )

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'lecturer': forms.TextInput(attrs={'class': 'form-control'}),
            'credit': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'year': forms.TextInput(attrs={'class': 'form-control'}),
            'room': forms.TextInput(attrs={'class': 'form-control'}),
        }

story4/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import inlineformset_factory, modelformset_factory
from django.contrib.auth.decorators import login_required
from .forms import CourseForm, PersonForm
from .models import Course, Activity, Person
#TODO Implement


def index(request):
    return render(request, 'story4/index.html')


def gallery(request):
    return render(request, 'story4/gallery.html')

@login_required(login_url='story7:login')
def course_add(request):
    form = CourseForm()
    if request.method == "POST":
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('profile:course')
    context = {
        'form': form
    }
    return render(request, 'story4/form.html', context)


@login_required(login_url='story7:login')
def course_update(request, pk):
    course = Course.objects.get(id=pk)
    form = CourseForm(instance=course)
    if request.method == "POST":
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect('profile:course')
    context = {
        'course': course,
        'form': form
    }
    return render(request, 'story4/form.html', context)


@login_required(login_url='story7:login')
def course_delete(request, pk):
    course = Course.objects.get(id=pk)
    if request.method == "POST":
        course.delete()
        return redirect('profile:course')
    context = {
        'course': course
    }
    return render(request, 'story4/delete.html', context)


@login_required(login_url='story7:login')
def course_detail(request, pk):
    course = Course.objects.get(id=pk)
    context = {
        'course': course
    }
    return render(request, 'story4/detail.html', context)

def course(request):
    course = Course.objects.all()
    context = {
        'course': course
    }
    return render(request, 'story4/course.html', context)

def activity(request):
    activity_1 = Person.objects.filter(activity__name="DOTA")
    activity_2 = Person.objects.filter(activity__name="LoL")
    activity_3 = Person.objects.filter(activity__name="Genshin")
    context = {'activity_1': activity_1, 'activity_2': activity_2, 'activity_3': activity_3,}
    return render(request, 'story4/activity.html', context)


@login_required(login_url='story7:login')
def register(request, pk):
    PersonFormSet = inlineformset_factory(Activity, Person, fields=('name',))
    activity = Activity.objects.get(id=pk)
    formset = PersonFormSet(instance=activity)
    if request.method == "POST":
        formset = PersonFormSet(request.POST, instance=activity)
        if formset.is_valid():
            formset.save()
            return redirect('profile:activity')
    return render(request, 'story4/register.html', {'formset': formset})

story4/templates/story4/activity.html
{% extends "base.html" %}

{% block meta %}
<title>Activity</title>
{% endblock meta %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/activity.css' %}">
<div class="container-fluid">
    <div class="header">
        <h1 class="text-center" style="color: #63526C;">My Activity</h1>
    </div>
    <div class="row">
        <div class="column text-center">
            <h3>Mabar DOTA</h3>
            <img src="{% static 'img/dota-2-logo.0.jpg' %}" style="width:100%">
            <a class="btn btn-dark mr-2 mt-2 mb-5" href="/register/1">Register</a>
            <table class="table">
                <thead class="thead-dark">
                    <th scope="col">Nama Teman</th>
                </thead>
                <tbody>
                    {% for i in activity_1 %}
                    <tr>
                        <td class="table-dark">{{ i.name }} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="column text-center">
            <h3>Mabar LoL</h3>
            <img src="{% static 'img/Home-page.jpg' %}" style="width:100%">
            <a class="btn btn-dark mr-2 mt-2 mb-5" href="/register/2">Register</a>
            <table class="table">
                <thead class="thead-dark">
                    <th scope="col">Nama Teman</th>
                </thead>
                <tbody>
                    {% for i in activity_2 %}
                    <tr>
                        <td class="table-dark">{{ i.name }} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="column text-center">
            <h3>Mabar Genshin</h3>
            <img src="{% static 'img/Genshin-Impact-image-new-1.png' %}" style="width:100%">
            <a class="btn btn-dark mr-2 mt-2 mb-5" href="/register/3">Register</a>
            <table class="table">
                <thead class="thead-dark">
                    <th scope="col">Nama Teman</th>
                </thead>
                <tbody>
                    {% for i in activity_3 %}
                    <tr>
                        <td class="table-dark">{{ i.name }} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% for i in activity %}
            <a class="btn btn-dark mr-2 mt-2 mb-5" href="{% url 'profile:register' %}">Register</a>
        {% endfor %}
    </div>
</div>
{% endblock %}

story4/templates/story4/course.html
{% extends "base.html" %}

{% block meta %}
<title>Course</title>
{% endblock meta %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-10">
        <h1 class="text-center" style="color: #63526C">My Courses</h1>
        <table class="table">
            <thead class="thead-dark">
                <th scope="col-2">Mata Kuliah</th>
                <th scope="col-2">Options</th>
            </thead>
            <tbody>
                {% for i in course %}
                <tr>
                    <td class="table-dark">{{ i.name }} </td>
                    <td class="table-dark">
                        <a class="btn btn-success mr-1 mb-1" href="{% url 'profile:detail_course' i.id %}">Detail</a> 
                        <a class="btn btn-info mr-1 mb-1" href="{% url 'profile:update_course' i.id %}">Update</a>
                        <a class="btn btn-danger mr-1 mb-1" href="{% url 'profile:delete_course' i.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

story4/templates/story4/delete.html
{% extends "base.html" %}

{% block meta %}
<title>Delete Course</title>
{% endblock meta %}

{% block content %}
<div class="delete-form">
    <form action="{% url 'profile:delete_course' course.id %}" method="POST">
        {% csrf_token %}
        <div class="row justify-content-center">
            <h1 class="text-center" style="color: #63526C; margin-top: 60px;">Delete {{ course.name }}?</h1>
        </div>
        <div class="text-center">
            <a class="btn btn-primary mr-2" href="{% url 'profile:course' %}">Cancel</a>
            <button type="submit" class="btn btn-danger">Confirm</button>
        </div>
    </form>
</div>
{% endblock %}

story4/templates/story4/detail.html
{% extends "base.html" %}

{% block meta %}
<title>Detail Course</title>
{% endblock meta %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-6">
        <h1 class="text-center" style="color: #63526C">My Courses</h1>
        <table class="table">
                <tr>
                    <td class="table-dark">Mata Kuliah</td>
                    <td class="table-dark">{{ course.name }} </td>
                </tr>
                <tr>
                    <td class="table-dark">Dosen</td>
                    <td class="table-dark">{{ course.lecturer }} </td>
                </tr>
                <tr>
                    <td class="table-dark">Deskripsi</td>
                    <td class="table-dark">{{ course.description }} </td>
                </tr>
                <tr>
                    <td class="table-dark">Semester</td>
                    <td class="table-dark">{{ course.year }} </td>
                </tr>
                <tr>
                    <td class="table-dark">SKS</td>
                    <td class="table-dark">{{ course.credit }} </td>
                </tr>
                <tr>
                    <td class="table-dark">Ruang</td>
                    <td class="table-dark">{{ course.room }} </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

story4/templates/story4/form.html
{% extends "base.html" %}

{% block meta %}
<title>Add Course</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid">
    <form action="" class="main-form" id="form" method="POST">
        <h1 class="text-center">Course Forms</h1>
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="name">Mata Kuliah</label>
                    {{ form.name }}
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="lecturer">Dosen</label>
                    {{ form.lecturer }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <label for="description">Deskripsi</label>
                    {{ form.description }}
                </div>
            </div>
            <div class="col-12">
                <div class="dropdown">
                    <label for="year">Semester/Tahun Ajaran</label>
                    {{ form.year }}
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <label for="credit">SKS</label>
                    {{ form.credit }}
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <label for="room">Ruang</label>
                    {{ form.room }}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
</div>
{% endblock %}

story4/templates/story4/gallery.html
{% extends "base.html" %}

{% block meta %}
<title>Gallery</title>
{% endblock meta %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/gallery.css' %}">
<div class="container-fluid">
    <div class="header">
        <h1 class="text-center" style="color: #63526C;">My Gallery</h1>
    </div>
    <div class="row ">
        <div class="column">
            <img src="{% static 'img/EjabhrpUcAcpHr0.jpg' %}" style="width:100%">
        </div>
        <div class="column">
            <img src="{% static 'img/EjaXHMlVkAAeUw9.jpg' %}" style="width:100%">
        </div>
        <div class="column">
            <img src="{% static 'img/jojinectar-819x1024.jpg' %}" style="width:100%">
        </div>
    </div>
</div>
{% endblock %}

story4/templates/story4/index.html
{% extends "base.html" %}

{% block meta %}
<title>Profile</title>
{% endblock meta %}

{% block content %}
<section class="landing-page" id="home">
    <div class="container-1">
        <div class="landing-page-column">
            <div id="landing-page-caption1">
                Welcome
            </div>
            <div id="landing-page-caption2">
                {{ request.user.username|default:"Guest" }}!
            </div>
        </div>
    </div>
</section>
<div class="section-a" id="resume">
    <h1>Resume</h1>
    <div class="container-2">
        <div class="education">
            <h3>Education</h3>
            <div id="section-a-content1">
                <h4>High School</h4>
                <h3>78 Senior High School, Jakarta</h3>
                <h5>2017 - 2019</h5>
            </div>
            <div id="section-a-content3">
                <h4>University</h4>
                <h3>Faculty of Computer Science, University of Indonesia</h3>
                <h5>2019 - Present</h5>
            </div>
        </div>
        <div class="experiences">
            <h3>Experiences</h3>
            <div id="section-a-content2">
                <h4>COMPFEST</h4>
                <h3>Finance Staff</h3>
                <h5>2020</h5>
            </div>
        </div>
    </div>
</div>
<section class="section-b" id="about">
    <h1>About Me</h1>
    <div class="container-3">
        <div class="contact">
            <div id="section-b-content1">
                <h2>Contact</h2>
                <h3>EMAIL</h3>
                <h4>frsardhafa@gmail.com</h4>
                <h3>PHONE</h3>
                <h4>+62 878 8605 4739</h4>
                <h3>ADDRESS</h3>
                <h4>Taman Alfa Indah B5/6, Joglo, Kembangan, West Jakarta, 11640</h4>
            </div>
        </div>
        <div class="about">
            <div id="section-b-content2">
                <p>Hi, my name is Faris Ardhafa. I’m a student at University of Indonesia. I specialize in Python and
                    Java language.
                    Currently I’m learning web development and this profile is one of the example. I will add more of my
                    skills and
                    experiences in the future. Thank you and have a great day!
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

 

story4/templates/story4/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block meta %}
<title>Register Activity</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid">
    <form action="" class="main-form" id="form" method="POST">
        <h1 class="text-center">Register Forms</h1>
        {% csrf_token %}
        <div class="row">
            <div class="col md-4">
                <div class="form-group">
                    {{ formset.management_form }}
                    {% for form in formset %}
                    {{ form|crispy }}
                    {% endfor %}
                    <br>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
</div>

{% endblock %}