ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('story-1/', include('story1.urls')),
    path('', include('story7.urls')),
]

story1/urls.py
from django.urls import path, include
from . import views
#url for app
app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

#url for app, add your URL Configuration
app_name = 'profile'

urlpatterns = [
    #TODO Implement this
    path('', views.index, name='index'),
    path('gallery/', views.gallery, name='gallery'),
    path('course/add', views.course_add, name='add_course'),
    path('course/update/<str:pk>', views.course_update, name='update_course'),
    path('course/delete/<str:pk>', views.course_delete, name='delete_course'),
    path('course/detail/<str:pk>', views.course_detail, name='detail_course'),
    path('course/', views.course, name='course'),
    path('activity/', views.activity, name='activity'),
    path('register/<str:pk>', views.register, name='register'),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('accordion/', views.accordion, name='accordion'),
    path('booksfinder/', views.booksfinder, name='booksfinder'),
    path('user/login', views.loginpage, name='login'),
    path('user/logout', views.logoutuser, name='logout'),
    path('user/register', views.registeruser, name='registeruser'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- Roboto fonts-->
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar navbar-expand-lg site-navbar navbar-light bg-light" id="pb-navbar">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09"
        aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample09">
        <ul class="navbar-nav">
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Home
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'profile:index' %}">Landing Page</a>
              <a class="dropdown-item" href="#resume">Resume</a>
              <a class="dropdown-item" href="#about">About</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Course
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'profile:course' %}">My Course</a>
              <a class="dropdown-item" href="{% url 'profile:add_course' %}">Add Course</a>
            </div>
          </li>
          <li class="nav-item"><a class="nav-link" href="{% url 'profile:gallery' %}">Galery</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'profile:activity' %}">Activity</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'story1:index' %}">Story 1</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'story7:accordion' %}">Accordion</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'story7:booksfinder' %}">Books</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'story7:login' %}">Login</a></li>
        </ul>
      </div>
      <span id="hello-msg">Hello, {{ request.user }}</span>
      <span><a href="{% url 'story7:logout' %}">Logout</a></span>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>